version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_pass
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=flask_db
      - DATABASE_USER=flask_user
      - DATABASE_PASSWORD=flask_pass
    command: ["flask", "run"]
volumes:
  db_data:
